#!/bin/bash
if [[ -z ${1} ]] ; then
    if ! ssh -Y -o ConnectTimeout=1 aislan@192.168.73.3 '${1} &' ; then
        echo -e "\e[1;31mError executing \e[1;30m${1}\e[1;31m on brix!"
    fi
elif ! ssh -Y -o ConnectTimeout=1 aislan@192.168.73.3 ; then
    echo -e "\e[1;31mConnection to brix was refused!"
fi
