#!/bin/bash

erase_auxiliar()
{
    rm -f *.aux ;
    rm -f *.bbl ;
    rm -f *.blg ;
    rm -f *.log ;
    rm -f *.brf ;
    rm -f *.idx ;
    rm -f *.lof ;
    rm -f *.lot ;
    rm -f *.toc ;
    echo "Auxiliar files were erased!"
}

control_c()
{
    kill $EVINCE 2> /dev/null ;
    rm -f aux.* ;
    rm -f show.pdf ;
    echo -e "\e[G\e[1;31mFinalizing the looping compilation.\e[0m"
    exit
}

if [[ -n ${5} ]]; then
    echo "Too much arguments!" ;
    exit
fi

if [[ ${1} = "-h" ]]; then
    echo "Available commands:" ;
    echo "    -s = Silent mode, not sending popup notifications." ;
    echo "    -c = Compile, compiles the .tex file completely." ;
    echo "    -f = FullCompile, erases all auxiliar files and compiles everything." ;
    echo "    -l = Looping Compilation, keeps compiling the archive every time it is saved." ;
    echo "    -x = Clean Folder, erases auxiliar files after compilation." ;
    echo "    -e = Erase Only, just erases auxiliar files, without compilation." ;
    echo "    -h = Help." ;
    exit
fi

FILE="*.tex"
SILENT=false
TYPE=""
CLEAR=false
LOOP=false
LAST=""
BLAST=""
AUX=""
EVINCE=""

for i in ${1} ${2} ${3} ${4}
do
    if [[ -e $i ]]; then
        if [[ "$FILE" = "*.tex" ]]; then
            FILE=$i
        else
            echo "Too much file options, use just one!" ;
            exit
        fi
    elif [[ $i = '-s' ]]; then
        SILENT=true
    elif [[ $i = '-c' ]]; then
        TYPE="c"
    elif [[ $i = '-f' ]]; then
        TYPE="f"
    elif [[ $i = '-x' ]]; then
        CLEAR=true
    elif [[ $i = '-e' ]]; then
        erase_auxiliar ;
        exit
    elif [[ $i = '-l' ]]; then
        LOOP=true
    fi
done

if $LOOP && [[ $TYPE != "" ]]; then
    echo "The looping option conflicts with the compiling option."
fi

AUX=( $FILE )

if [[ "$FILE" = "*.tex" && ${#AUX[@]} -ne 1 ]]; then
    echo "Too much file options, use just one!" ;
    exit
fi

if $LOOP; then
    echo -e "\e[0mCompiling!"
    if pdflatex -halt-on-error -jobname=aux -draftmode $FILE > /dev/null ; then
        echo -e "\e[F\e[2KCompiling!!"
        if ! bibtex aux.aux > /dev/null ; then
            echo -e "\e[F\e[2K\e[1;31mError compiling bibtex" ;
        fi
        pdflatex -halt-on-error -jobname=aux -draftmode $FILE > /dev/null ;
        echo -e "\e[F\e[2KCompiling!!!"
        pdflatex -halt-on-error -jobname=aux $FILE > /dev/null ;
        mv aux.pdf show.pdf ;
        echo -e "\e[F\e[2K\e[1;36mCompiled!"
        evince show.pdf > /dev/null & 
        EVINCE=$!
    else
        echo -e "\e[F\e[2K\e[1;31mCompilation Error, try again." ;
        exit
    fi
    LAST=$(stat -c%Y $FILE txt/* *.bib)

    trap control_c SIGINT

    echo -e "\e[1;36mRunning looping compilation.\e[0m"
    while :
    do
        sleep 1
        ACT=$(stat -c%Y $FILE txt/* *.bib)

        if ! ps $EVINCE > /dev/null ; then
            control_c
        fi

        if [[ $LAST -ne $ACT ]]; then
            echo -e "\e[0mCompiling!" ;
            LAST=$ACT ;
            if pdflatex -halt-on-error -jobname=aux -draftmode $FILE > /dev/null ; then
                echo -e "\e[F\e[2KCompiling!!" ;
                if ! bibtex aux.aux > /dev/null ; then
                    echo -e "\e[F\e[2K\e[1;31mError compiling bibtex"
                fi
                pdflatex -halt-on-error -jobname=aux -draftmode $FILE > /dev/null ;
                echo -e "\e[F\e[2KCompiling!!!" ;
                pdflatex -halt-on-error -jobname=aux $FILE > /dev/null ;
                mv aux.pdf show.pdf ;
                echo -e "\e[F\e[2K\e[1;36mCompiled!"
            else
                echo -e "\e[F\e[2K\e[1;31mCompilation Error!"
            fi
        fi
    done
fi

if [[ $TYPE = "f" ]]; then
    erase_auxiliar ;
    rm -f *.pdf
fi

if [[ $TYPE = "f" || $TYPE = "c" ]]; then
    if ! pdflatex -halt-on-error -draftmode $FILE ; then
        if $SILENT; then
            echo "Latex Compilation Error: Something went wrong in the compilation process."
        else
            notify-send 'Latex Compilation Error' 'Something went wrong in the compilation process.' --urgency=critical ;
            exit
        fi
    fi

    if ! bibtex *.aux ; then
        if $SILENT; then
            echo "Bibtex Compilation Error: Something went wrong in the compilation process."
        else
            notify-send 'Bibtex Compilation Error' 'Something went wrong in the compilation process.' --urgency=critical ;
            exit
        fi
    fi

    pdflatex -halt-on-error -draftmode $FILE
fi

pdflatex -halt-on-error $FILE

if $CLEAR; then
    echo $CLEAR ;
    erase_auxiliar
fi

if $SILENT; then
    echo "Latex Compilation Success: Tex file was succesfully compiled."
else
    notify-send 'Latex Compilation Success' 'Tex file was succesfully compiled.'
fi
